/*
 * Copyright (c) 2025 Espressif Systems (Shanghai) Co., Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#define CONFIG_SOC_ADC_ARBITER_SUPPORTED 1
#define CONFIG_SOC_ADC_ATTEN_NUM 4
#define CONFIG_SOC_ADC_CALIBRATION_V1_SUPPORTED 1
#define CONFIG_SOC_ADC_DIG_CTRL_SUPPORTED 1
#define CONFIG_SOC_ADC_DIG_IIR_FILTER_SUPPORTED 1
#define CONFIG_SOC_ADC_DIGI_CONTROLLER_NUM 1
#define CONFIG_SOC_ADC_DIGI_DATA_BYTES_PER_CONV 4
#define CONFIG_SOC_ADC_DIGI_IIR_FILTER_NUM 2
#define CONFIG_SOC_ADC_DIGI_MAX_BITWIDTH 12
#define CONFIG_SOC_ADC_DIGI_MIN_BITWIDTH 12
#define CONFIG_SOC_ADC_DIGI_MONITOR_NUM 2
#define CONFIG_SOC_ADC_DIGI_RESULT_BYTES 4
#define CONFIG_SOC_ADC_DMA_SUPPORTED 1
#define CONFIG_SOC_ADC_MAX_CHANNEL_NUM 5
#define CONFIG_SOC_ADC_MONITOR_SUPPORTED 1
#define CONFIG_SOC_ADC_PATT_LEN_MAX 8
#define CONFIG_SOC_ADC_PERIPH_NUM 2
#define CONFIG_SOC_ADC_RTC_MAX_BITWIDTH 12
#define CONFIG_SOC_ADC_RTC_MIN_BITWIDTH 12
#define CONFIG_SOC_ADC_SAMPLE_FREQ_THRES_HIGH 83333
#define CONFIG_SOC_ADC_SAMPLE_FREQ_THRES_LOW 611
#define CONFIG_SOC_ADC_SELF_HW_CALI_SUPPORTED 1
#define CONFIG_SOC_ADC_SHARED_POWER 1
#define CONFIG_SOC_ADC_SUPPORTED 1
#define CONFIG_SOC_AES_GDMA 1
#define CONFIG_SOC_AES_SUPPORT_AES_128 1
#define CONFIG_SOC_AES_SUPPORT_AES_256 1
#define CONFIG_SOC_AES_SUPPORT_DMA 1
#define CONFIG_SOC_AES_SUPPORTED 1
#define CONFIG_SOC_AHB_GDMA_SUPPORTED 1
#define CONFIG_SOC_AHB_GDMA_VERSION 1
#define CONFIG_SOC_APB_BACKUP_DMA 1
#define CONFIG_SOC_ASSIST_DEBUG_SUPPORTED 1
#define CONFIG_SOC_ASYNC_MEMCPY_SUPPORTED 1
#define CONFIG_SOC_BLE_50_SUPPORTED 1
#define CONFIG_SOC_BLE_DEVICE_PRIVACY_SUPPORTED 1
#define CONFIG_SOC_BLE_MESH_SUPPORTED 1
#define CONFIG_SOC_BLE_SUPPORTED 1
#define CONFIG_SOC_BLUFI_SUPPORTED 1
#define CONFIG_SOC_BOD_SUPPORTED 1
#define CONFIG_SOC_BROWNOUT_RESET_SUPPORTED 1
#define CONFIG_SOC_BT_SUPPORTED 1
#define CONFIG_SOC_CACHE_MEMORY_IBANK_SIZE 0x4000
#define CONFIG_SOC_CLK_LP_FAST_SUPPORT_XTAL_D2 1
#define CONFIG_SOC_CLK_RC_FAST_D256_SUPPORTED 1
#define CONFIG_SOC_CLK_RC_FAST_SUPPORT_CALIBRATION 1
#define CONFIG_SOC_CLK_TREE_SUPPORTED 1
#define CONFIG_SOC_CLK_XTAL32K_SUPPORTED 1
#define CONFIG_SOC_COEX_HW_PTI 1
#define CONFIG_SOC_CPU_BREAKPOINTS_NUM 8
#define CONFIG_SOC_CPU_CORES_NUM 1
#define CONFIG_SOC_CPU_HAS_CSR_PC 1
#define CONFIG_SOC_CPU_HAS_FLEXIBLE_INTC 1
#define CONFIG_SOC_CPU_INTR_NUM 32
#define CONFIG_SOC_CPU_WATCHPOINT_MAX_REGION_SIZE 0x80000000
#define CONFIG_SOC_CPU_WATCHPOINTS_NUM 8
#define CONFIG_SOC_DEDIC_GPIO_IN_CHANNELS_NUM 8
#define CONFIG_SOC_DEDIC_GPIO_OUT_CHANNELS_NUM 8
#define CONFIG_SOC_DEDIC_PERIPH_ALWAYS_ENABLE 1
#define CONFIG_SOC_DEDICATED_GPIO_SUPPORTED 1
#define CONFIG_SOC_DEEP_SLEEP_SUPPORTED 1
#define CONFIG_SOC_DIG_SIGN_SUPPORTED 1
#define CONFIG_SOC_DS_KEY_CHECK_MAX_WAIT_US 1100
#define CONFIG_SOC_DS_KEY_PARAM_MD_IV_LENGTH 16
#define CONFIG_SOC_DS_SIGNATURE_MAX_BIT_LEN 3072
#define CONFIG_SOC_EFUSE_BLOCK9_KEY_PURPOSE_QUIRK 1
#define CONFIG_SOC_EFUSE_DIS_DIRECT_BOOT 1
#define CONFIG_SOC_EFUSE_DIS_DOWNLOAD_ICACHE 1
#define CONFIG_SOC_EFUSE_DIS_ICACHE 1
#define CONFIG_SOC_EFUSE_DIS_PAD_JTAG 1
#define CONFIG_SOC_EFUSE_DIS_USB_JTAG 1
#define CONFIG_SOC_EFUSE_HAS_EFUSE_RST_BUG 1
#define CONFIG_SOC_EFUSE_KEY_PURPOSE_FIELD 1
#define CONFIG_SOC_EFUSE_REVOKE_BOOT_KEY_DIGESTS 1
#define CONFIG_SOC_EFUSE_SECURE_BOOT_KEY_DIGESTS 3
#define CONFIG_SOC_EFUSE_SOFT_DIS_JTAG 1
#define CONFIG_SOC_EFUSE_SUPPORTED 1
#define CONFIG_SOC_FLASH_ENC_SUPPORTED 1
#define CONFIG_SOC_FLASH_ENCRYPTED_XTS_AES_BLOCK_MAX 32
#define CONFIG_SOC_FLASH_ENCRYPTION_XTS_AES 1
#define CONFIG_SOC_FLASH_ENCRYPTION_XTS_AES_128 1
#define CONFIG_SOC_GDMA_GROUPS_MAX 1
#define CONFIG_SOC_GDMA_NUM_GROUPS_MAX 1
#define CONFIG_SOC_GDMA_PAIRS_PER_GROUP_MAX 3
#define CONFIG_SOC_GDMA_SUPPORTED 1
#define CONFIG_SOC_GDMA_TX_RX_SHARE_INTERRUPT 1
#define CONFIG_SOC_GPIO_CLOCKOUT_BY_GPIO_MATRIX 1
#define CONFIG_SOC_GPIO_CLOCKOUT_CHANNEL_NUM 1
#define CONFIG_SOC_GPIO_DEEP_SLEEP_WAKE_SUPPORTED_PIN_CNT 1
#define CONFIG_SOC_GPIO_DEEP_SLEEP_WAKE_VALID_GPIO_MASK 0
#define CONFIG_SOC_GPIO_FILTER_CLK_SUPPORT_APB 1
#define CONFIG_SOC_GPIO_IN_RANGE_MAX 1
#define CONFIG_SOC_GPIO_OUT_RANGE_MAX 1
#define CONFIG_SOC_GPIO_PIN_COUNT 22
#define CONFIG_SOC_GPIO_PORT 1
#define CONFIG_SOC_GPIO_SUPPORT_DEEPSLEEP_WAKEUP 1
#define CONFIG_SOC_GPIO_SUPPORT_FORCE_HOLD 1
#define CONFIG_SOC_GPIO_SUPPORT_HOLD_IO_IN_DSLP 1
#define CONFIG_SOC_GPIO_SUPPORT_PIN_GLITCH_FILTER 1
#define CONFIG_SOC_GPIO_VALID_DIGITAL_IO_PAD_MASK 0x00000000003FFFC0
#define CONFIG_SOC_GPSPI_SUPPORTED 1
#define CONFIG_SOC_GPTIMER_SUPPORTED 1
#define CONFIG_SOC_HMAC_SUPPORTED 1
#define CONFIG_SOC_HP_I2C_NUM 1
#define CONFIG_SOC_I2C_CMD_REG_NUM 8
#define CONFIG_SOC_I2C_FIFO_LEN 32
#define CONFIG_SOC_I2C_NUM 1
#define CONFIG_SOC_I2C_SLAVE_CAN_GET_STRETCH_CAUSE 1
#define CONFIG_SOC_I2C_SLAVE_SUPPORT_BROADCAST 1
#define CONFIG_SOC_I2C_SLAVE_SUPPORT_I2CRAM_ACCESS 1
#define CONFIG_SOC_I2C_SUPPORT_10BIT_ADDR 1
#define CONFIG_SOC_I2C_SUPPORT_HW_CLR_BUS 1
#define CONFIG_SOC_I2C_SUPPORT_RTC 1
#define CONFIG_SOC_I2C_SUPPORT_SLAVE 1
#define CONFIG_SOC_I2C_SUPPORT_XTAL 1
#define CONFIG_SOC_I2C_SUPPORTED 1
#define CONFIG_SOC_I2S_HW_VERSION_2 1
#define CONFIG_SOC_I2S_NUM 1
#define CONFIG_SOC_I2S_PDM_MAX_RX_LINES 1
#define CONFIG_SOC_I2S_PDM_MAX_TX_LINES 2
#define CONFIG_SOC_I2S_SUPPORTED 1
#define CONFIG_SOC_I2S_SUPPORTS_PCM 1
#define CONFIG_SOC_I2S_SUPPORTS_PCM2PDM 1
#define CONFIG_SOC_I2S_SUPPORTS_PDM 1
#define CONFIG_SOC_I2S_SUPPORTS_PDM_RX 1
#define CONFIG_SOC_I2S_SUPPORTS_PDM_TX 1
#define CONFIG_SOC_I2S_SUPPORTS_PLL_F160M 1
#define CONFIG_SOC_I2S_SUPPORTS_TDM 1
#define CONFIG_SOC_I2S_SUPPORTS_XTAL 1
#define CONFIG_SOC_LEDC_CHANNEL_NUM 6
#define CONFIG_SOC_LEDC_SUPPORT_APB_CLOCK 1
#define CONFIG_SOC_LEDC_SUPPORT_FADE_STOP 1
#define CONFIG_SOC_LEDC_SUPPORT_XTAL_CLOCK 1
#define CONFIG_SOC_LEDC_SUPPORTED 1
#define CONFIG_SOC_LEDC_TIMER_BIT_WIDTH 14
#define CONFIG_SOC_LEDC_TIMER_NUM 1
#define CONFIG_SOC_LIGHT_SLEEP_SUPPORTED 1
#define CONFIG_SOC_LP_PERIPH_SHARE_INTERRUPT 1
#define CONFIG_SOC_LP_TIMER_BIT_WIDTH_HI 1
#define CONFIG_SOC_LP_TIMER_BIT_WIDTH_LO 1
#define CONFIG_SOC_MAC_BB_PD_MEM_SIZE 192
#define CONFIG_SOC_MEMPROT_CPU_PREFETCH_PAD_SIZE 16
#define CONFIG_SOC_MEMPROT_MEM_ALIGN_SIZE 512
#define CONFIG_SOC_MEMPROT_SUPPORTED 1
#define CONFIG_SOC_MEMSPI_IS_INDEPENDENT 1
#define CONFIG_SOC_MEMSPI_SRC_FREQ_20M_SUPPORTED 1
#define CONFIG_SOC_MEMSPI_SRC_FREQ_26M_SUPPORTED 1
#define CONFIG_SOC_MEMSPI_SRC_FREQ_40M_SUPPORTED 1
#define CONFIG_SOC_MEMSPI_SRC_FREQ_80M_SUPPORTED 1
#define CONFIG_SOC_MMU_LINEAR_ADDRESS_REGION_NUM 1
#define CONFIG_SOC_MMU_PERIPH_NUM 1
#define CONFIG_SOC_MPI_MEM_BLOCKS_NUM 1
#define CONFIG_SOC_MPI_OPERATIONS_NUM 1
#define CONFIG_SOC_MPI_SUPPORTED 1
#define CONFIG_SOC_MPU_MIN_REGION_SIZE 0x20000000
#define CONFIG_SOC_MPU_REGIONS_MAX_NUM 8
#define CONFIG_SOC_MWDT_SUPPORT_XTAL 1
#define CONFIG_SOC_PHY_COMBO_MODULE 1
#define CONFIG_SOC_PHY_DIG_REGS_MEM_SIZE 21
#define CONFIG_SOC_PHY_SUPPORTED 1
#define CONFIG_SOC_PM_CPU_RETENTION_BY_RTCCNTL 1
#define CONFIG_SOC_PM_MODEM_PD_BY_SW 1
#define CONFIG_SOC_PM_MODEM_RETENTION_BY_BACKUPDMA 1
#define CONFIG_SOC_PM_SUPPORT_BT_PD 1
#define CONFIG_SOC_PM_SUPPORT_BT_WAKEUP 1
#define CONFIG_SOC_PM_SUPPORT_CPU_PD 1
#define CONFIG_SOC_PM_SUPPORT_MAC_BB_PD 1
#define CONFIG_SOC_PM_SUPPORT_RC_FAST_PD 1
#define CONFIG_SOC_PM_SUPPORT_VDDSDIO_PD 1
#define CONFIG_SOC_PM_SUPPORT_WIFI_PD 1
#define CONFIG_SOC_PM_SUPPORT_WIFI_WAKEUP 1
#define CONFIG_SOC_PM_SUPPORTED 1
#define CONFIG_SOC_RMT_CHANNELS_PER_GROUP 4
#define CONFIG_SOC_RMT_GROUPS 1
#define CONFIG_SOC_RMT_MEM_WORDS_PER_CHANNEL 48
#define CONFIG_SOC_RMT_RX_CANDIDATES_PER_GROUP 2
#define CONFIG_SOC_RMT_SUPPORT_APB 1
#define CONFIG_SOC_RMT_SUPPORT_RC_FAST 1
#define CONFIG_SOC_RMT_SUPPORT_RX_DEMODULATION 1
#define CONFIG_SOC_RMT_SUPPORT_RX_PINGPONG 1
#define CONFIG_SOC_RMT_SUPPORT_TX_ASYNC_STOP 1
#define CONFIG_SOC_RMT_SUPPORT_TX_CARRIER_DATA_ONLY 1
#define CONFIG_SOC_RMT_SUPPORT_TX_LOOP_COUNT 1
#define CONFIG_SOC_RMT_SUPPORT_TX_SYNCHRO 1
#define CONFIG_SOC_RMT_SUPPORT_XTAL 1
#define CONFIG_SOC_RMT_SUPPORTED 1
#define CONFIG_SOC_RMT_TX_CANDIDATES_PER_GROUP 2
#define CONFIG_SOC_RNG_SUPPORTED 1
#define CONFIG_SOC_RSA_MAX_BIT_LEN 3072
#define CONFIG_SOC_RTC_CNTL_CPU_PD_DMA_BUS_WIDTH 128
#define CONFIG_SOC_RTC_CNTL_CPU_PD_REG_FILE_NUM 108
#define CONFIG_SOC_RTC_FAST_MEM_SUPPORTED 1
#define CONFIG_SOC_RTC_MEM_SUPPORTED 1
#define CONFIG_SOC_RTC_SLOW_CLK_SUPPORT_RC_FAST_D256 1
#define CONFIG_SOC_RTCIO_PIN_COUNT 0
#define CONFIG_SOC_SDM_CHANNELS_PER_GROUP 4
#define CONFIG_SOC_SDM_CLK_SUPPORT_APB 1
#define CONFIG_SOC_SDM_GROUPS 1
#define CONFIG_SOC_SDM_SUPPORTED 1
#define CONFIG_SOC_SECURE_BOOT_SUPPORTED 1
#define CONFIG_SOC_SECURE_BOOT_V2_RSA 1
#define CONFIG_SOC_SHA_DMA_MAX_BUFFER_SIZE 3968
#define CONFIG_SOC_SHA_GDMA 1
#define CONFIG_SOC_SHA_SUPPORT_DMA 1
#define CONFIG_SOC_SHA_SUPPORT_RESUME 1
#define CONFIG_SOC_SHA_SUPPORT_SHA1 1
#define CONFIG_SOC_SHA_SUPPORT_SHA224 1
#define CONFIG_SOC_SHA_SUPPORT_SHA256 1
#define CONFIG_SOC_SHA_SUPPORTED 1
#define CONFIG_SOC_SHARED_IDCACHE_SUPPORTED 1
#define CONFIG_SOC_SLEEP_SYSTIMER_STALL_WORKAROUND 1
#define CONFIG_SOC_SLEEP_TGWDT_STOP_WORKAROUND 1
#define CONFIG_SOC_SPI_FLASH_SUPPORTED 1
#define CONFIG_SOC_SPI_MAX_CS_NUM 6
#define CONFIG_SOC_SPI_MAX_PRE_DIVIDER 16
#define CONFIG_SOC_SPI_MAXIMUM_BUFFER_SIZE 64
#define CONFIG_SOC_SPI_MEM_SUPPORT_AUTO_RESUME 1
#define CONFIG_SOC_SPI_MEM_SUPPORT_AUTO_SUSPEND 1
#define CONFIG_SOC_SPI_MEM_SUPPORT_AUTO_WAIT_IDLE 1
#define CONFIG_SOC_SPI_MEM_SUPPORT_CHECK_SUS 1
#define CONFIG_SOC_SPI_MEM_SUPPORT_CONFIG_GPIO_BY_EFUSE 1
#define CONFIG_SOC_SPI_MEM_SUPPORT_IDLE_INTR 1
#define CONFIG_SOC_SPI_MEM_SUPPORT_SW_SUSPEND 1
#define CONFIG_SOC_SPI_MEM_SUPPORT_WRAP 1
#define CONFIG_SOC_SPI_PERIPH_NUM 2
#define CONFIG_SOC_SPI_PERIPH_SUPPORT_CONTROL_DUMMY_OUT 1
#define CONFIG_SOC_SPI_SCT_BUFFER_NUM_MAX 1
#define CONFIG_SOC_SPI_SCT_CONF_BITLEN_MAX 1
#define CONFIG_SOC_SPI_SCT_REG_NUM 1
#define CONFIG_SOC_SPI_SCT_SUPPORTED 1
#define CONFIG_SOC_SPI_SLAVE_SUPPORT_SEG_TRANS 1
#define CONFIG_SOC_SPI_SUPPORT_CD_SIG 1
#define CONFIG_SOC_SPI_SUPPORT_CLK_APB 1
#define CONFIG_SOC_SPI_SUPPORT_CLK_XTAL 1
#define CONFIG_SOC_SPI_SUPPORT_CONTINUOUS_TRANS 1
#define CONFIG_SOC_SPI_SUPPORT_DDRCLK 1
#define CONFIG_SOC_SPI_SUPPORT_SLAVE_HD_VER2 1
#define CONFIG_SOC_SUPPORT_COEXISTENCE 1
#define CONFIG_SOC_SUPPORT_SECURE_BOOT_REVOKE_KEY 1
#define CONFIG_SOC_SUPPORTS_SECURE_DL_MODE 1
#define CONFIG_SOC_SYSTIMER_ALARM_MISS_COMPENSATE 1
#define CONFIG_SOC_SYSTIMER_ALARM_NUM 3
#define CONFIG_SOC_SYSTIMER_BIT_WIDTH_HI 20
#define CONFIG_SOC_SYSTIMER_BIT_WIDTH_LO 32
#define CONFIG_SOC_SYSTIMER_COUNTER_NUM 2
#define CONFIG_SOC_SYSTIMER_FIXED_DIVIDER 1
#define CONFIG_SOC_SYSTIMER_INT_LEVEL 1
#define CONFIG_SOC_SYSTIMER_SUPPORTED 1
#define CONFIG_SOC_TEMP_SENSOR_SUPPORTED 1
#define CONFIG_SOC_TEMPERATURE_SENSOR_SUPPORT_FAST_RC 1
#define CONFIG_SOC_TEMPERATURE_SENSOR_SUPPORT_XTAL 1
#define CONFIG_SOC_TIMER_GROUP_COUNTER_BIT_WIDTH 54
#define CONFIG_SOC_TIMER_GROUP_SUPPORT_APB 1
#define CONFIG_SOC_TIMER_GROUP_SUPPORT_XTAL 1
#define CONFIG_SOC_TIMER_GROUP_TIMERS_PER_GROUP 1
#define CONFIG_SOC_TIMER_GROUP_TOTAL_TIMERS 2
#define CONFIG_SOC_TIMER_GROUPS 2
#define CONFIG_SOC_TWAI_BRP_MAX 16384
#define CONFIG_SOC_TWAI_BRP_MIN 2
#define CONFIG_SOC_TWAI_CLK_SUPPORT_APB 1
#define CONFIG_SOC_TWAI_CONTROLLER_NUM 1
#define CONFIG_SOC_TWAI_SUPPORTED 1
#define CONFIG_SOC_TWAI_SUPPORTS_RX_STATUS 1
#define CONFIG_SOC_UART_BITRATE_MAX 5000000
#define CONFIG_SOC_UART_FIFO_LEN 128
#define CONFIG_SOC_UART_HP_NUM 1
#define CONFIG_SOC_UART_NUM 2
#define CONFIG_SOC_UART_SUPPORT_APB_CLK 1
#define CONFIG_SOC_UART_SUPPORT_FSM_TX_WAIT_SEND 1
#define CONFIG_SOC_UART_SUPPORT_RTC_CLK 1
#define CONFIG_SOC_UART_SUPPORT_WAKEUP_INT 1
#define CONFIG_SOC_UART_SUPPORT_XTAL_CLK 1
#define CONFIG_SOC_UART_SUPPORTED 1
#define CONFIG_SOC_UART_WAKEUP_SUPPORT_ACTIVE_THRESH_MODE 1
#define CONFIG_SOC_USB_SERIAL_JTAG_SUPPORTED 1
#define CONFIG_SOC_WDT_SUPPORTED 1
#define CONFIG_SOC_WIFI_CSI_SUPPORT 1
#define CONFIG_SOC_WIFI_FTM_SUPPORT 1
#define CONFIG_SOC_WIFI_GCMP_SUPPORT 1
#define CONFIG_SOC_WIFI_HW_TSF 1
#define CONFIG_SOC_WIFI_LIGHT_SLEEP_CLK_WIDTH 12
#define CONFIG_SOC_WIFI_MESH_SUPPORT 1
#define CONFIG_SOC_WIFI_PHY_NEEDS_USB_WORKAROUND 1
#define CONFIG_SOC_WIFI_SUPPORT_VARIABLE_BEACON_WINDOW 1
#define CONFIG_SOC_WIFI_SUPPORTED 1
#define CONFIG_SOC_WIFI_WAPI_SUPPORT 1
#define CONFIG_SOC_XT_WDT_SUPPORTED 1
#define CONFIG_SOC_XTAL_SUPPORT_40M 1

#define CONFIG_USJ_ENABLE_USB_SERIAL_JTAG 1
#define CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG_ENABLED 1

#define CONFIG_ESP_EFUSE_BLOCK_REV_MIN_FULL 0
#define CONFIG_ESP_EFUSE_BLOCK_REV_MAX_FULL 199

#define CONFIG_ESP_ROM_HAS_CRC_LE 1
#define CONFIG_ESP_ROM_HAS_CRC_BE 1
#define CONFIG_ESP_ROM_HAS_MZ_CRC32 1
#define CONFIG_ESP_ROM_HAS_JPEG_DECODE 1
#define CONFIG_ESP_ROM_UART_CLK_IS_XTAL 1
#define CONFIG_ESP_ROM_USB_SERIAL_DEVICE_NUM 3
#define CONFIG_ESP_ROM_HAS_RETARGETABLE_LOCKING 1
#define CONFIG_ESP_ROM_HAS_ERASE_0_REGION_BUG 1
#define CONFIG_ESP_ROM_HAS_ENCRYPTED_WRITES_USING_LEGACY_DRV 1
#define CONFIG_ESP_ROM_GET_CLK_FREQ 1
#define CONFIG_ESP_ROM_NEEDS_SWSETUP_WORKAROUND 1
#define CONFIG_ESP_ROM_HAS_LAYOUT_TABLE 1
#define CONFIG_ESP_ROM_HAS_SPI_FLASH 1
#define CONFIG_ESP_ROM_HAS_ETS_PRINTF_BUG 1
#define CONFIG_ESP_ROM_HAS_NEWLIB_NANO_FORMAT 1
#define CONFIG_ESP_ROM_NEEDS_SET_CACHE_MMU_SIZE 1
#define CONFIG_ESP_ROM_RAM_APP_NEEDS_MMU_INIT 1

#define CONFIG_EFUSE_MAX_BLK_LEN 256

#define CONFIG_ESP_MAC_ADDR_UNIVERSE_WIFI_STA 1
#define CONFIG_ESP_MAC_ADDR_UNIVERSE_WIFI_AP 1
#define CONFIG_ESP_MAC_ADDR_UNIVERSE_BT 1
#define CONFIG_ESP_MAC_ADDR_UNIVERSE_ETH 1
#define CONFIG_ESP_MAC_UNIVERSAL_MAC_ADDRESSES_FOUR 1
#define CONFIG_ESP32C3_UNIVERSAL_MAC_ADDRESSES_FOUR 1
#define CONFIG_ESP32C3_UNIVERSAL_MAC_ADDRESSES 4

#define CONFIG_ESP_PHY_MAX_TX_POWER 20
#define CONFIG_ESP_PHY_ENABLE_USB 1
#define CONFIG_ESP_PHY_RF_CAL_PARTIAL 1
#define CONFIG_ESP_PHY_CALIBRATION_MODE 0

#define CONFIG_ESP_SLEEP_WAIT_FLASH_READY_EXTRA_DELAY 0

#define CONFIG_ESP_SYSTEM_SINGLE_CORE_MODE 1

#define CONFIG_LOG_TAG_LEVEL_IMPL_CACHE_AND_LINKED_LIST 1
#define CONFIG_LOG_VERSION_1 1
#define CONFIG_LOG_VERSION 1

#define CONFIG_SPI_FLASH_ROM_DRIVER_PATCH 1

#include <nuttx/config.h>

#undef CONFIG_MBEDTLS_SSL_DTLS_CONNECTION_ID
#undef CONFIG_MBEDTLS_CHACHAPOLY_C
#undef CONFIG_MBEDTLS_POLY1305_C
#undef CONFIG_MBEDTLS_CHACHA20_C
#undef CONFIG_MBEDTLS_CAMELLIA_C
#undef CONFIG_MBEDTLS_NIST_KW_C
#undef CONFIG_MBEDTLS_RIPEMD160_C
#undef CONFIG_MBEDTLS_INTERNAL_MEM_ALLOC
#undef CONFIG_MBEDTLS_ASYMMETRIC_CONTENT_LEN
#undef CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN
#undef CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN
#undef CONFIG_MBEDTLS_SSL_KEEP_PEER_CERTIFICATE
#undef CONFIG_MBEDTLS_PKCS7_C
#undef CONFIG_MBEDTLS_CERTIFICATE_BUNDLE
#undef CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_FULL
#undef CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_MAX_CERTS
#undef CONFIG_MBEDTLS_HARDWARE_AES
#undef CONFIG_MBEDTLS_AES_USE_INTERRUPT
#undef CONFIG_MBEDTLS_HARDWARE_MPI
#undef CONFIG_MBEDTLS_MPI_USE_INTERRUPT
#undef CONFIG_MBEDTLS_HARDWARE_SHA
#undef CONFIG_MBEDTLS_ROM_MD5
#undef CONFIG_MBEDTLS_HAVE_TIME
#undef CONFIG_MBEDTLS_ECDSA_DETERMINISTIC
#undef CONFIG_MBEDTLS_SHA512_C
#undef CONFIG_MBEDTLS_TLS_SERVER_AND_CLIENT
#undef CONFIG_MBEDTLS_TLS_SERVER
#undef CONFIG_MBEDTLS_TLS_CLIENT
#undef CONFIG_MBEDTLS_TLS_ENABLED
#undef CONFIG_MBEDTLS_KEY_EXCHANGE_RSA
#undef CONFIG_MBEDTLS_KEY_EXCHANGE_ELLIPTIC_CURVE
#undef CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_RSA
#undef CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA
#undef CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA
#undef CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_RSA
#undef CONFIG_MBEDTLS_SSL_RENEGOTIATION
#undef CONFIG_MBEDTLS_SSL_PROTO_TLS1_2
#undef CONFIG_MBEDTLS_SSL_ALPN
#undef CONFIG_MBEDTLS_CLIENT_SSL_SESSION_TICKETS
#undef CONFIG_MBEDTLS_SERVER_SSL_SESSION_TICKETS
#undef CONFIG_MBEDTLS_AES_C
#undef CONFIG_MBEDTLS_CCM_C
#undef CONFIG_MBEDTLS_GCM_C
#undef CONFIG_MBEDTLS_PEM_PARSE_C
#undef CONFIG_MBEDTLS_PEM_WRITE_C
#undef CONFIG_MBEDTLS_X509_CRL_PARSE_C
#undef CONFIG_MBEDTLS_X509_CSR_PARSE_C
#undef CONFIG_MBEDTLS_ECP_C
#undef CONFIG_MBEDTLS_ECDH_C
#undef CONFIG_MBEDTLS_ECDSA_C
#undef CONFIG_MBEDTLS_SHA1_C
#undef CONFIG_MBEDTLS_ECP_DP_SECP192R1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_SECP224R1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_SECP384R1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_SECP521R1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_SECP192K1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_SECP224K1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_SECP256K1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_BP256R1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_BP384R1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_BP512R1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_CURVE25519_ENABLED
#undef CONFIG_MBEDTLS_ECP_NIST_OPTIM
#undef CONFIG_MBEDTLS_ECP_FIXED_POINT_OPTIM
#undef CONFIG_MBEDTLS_LARGE_KEY_SOFTWARE_MPI

#ifdef CONFIG_ESPRESSIF_BLE
#define CONFIG_BT_ENABLED 1
#define CONFIG_BT_NIMBLE_ENABLED 1
#define CONFIG_BT_CONTROLLER_ENABLED 1
#define CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_INTERNAL 1
#define CONFIG_BT_NIMBLE_LOG_LEVEL_INFO 1
#define CONFIG_BT_NIMBLE_LOG_LEVEL 1
#define CONFIG_BT_NIMBLE_MAX_CONNECTIONS 3
#define CONFIG_BT_NIMBLE_MAX_BONDS 3
#define CONFIG_BT_NIMBLE_MAX_CCCDS 8
#define CONFIG_BT_NIMBLE_L2CAP_COC_MAX_NUM 0
#define CONFIG_BT_NIMBLE_PINNED_TO_CORE 0
#define CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE 4096
#define CONFIG_BT_NIMBLE_ROLE_CENTRAL 1
#define CONFIG_BT_NIMBLE_ROLE_PERIPHERAL 1
#define CONFIG_BT_NIMBLE_ROLE_BROADCASTER 1
#define CONFIG_BT_NIMBLE_ROLE_OBSERVER 1
#define CONFIG_BT_NIMBLE_SECURITY_ENABLE 1
#define CONFIG_BT_NIMBLE_SM_LEGACY 1
#define CONFIG_BT_NIMBLE_SM_SC 1
#define CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_ENCRYPTION 1
#define CONFIG_BT_NIMBLE_SVC_GAP_DEVICE_NAME "nimble"
#define CONFIG_BT_NIMBLE_GAP_DEVICE_NAME_MAX_LEN 31
#define CONFIG_BT_NIMBLE_ATT_PREFERRED_MTU 256
#define CONFIG_BT_NIMBLE_SVC_GAP_APPEARANCE 0x0
#define CONFIG_BT_NIMBLE_MSYS_1_BLOCK_COUNT 12
#define CONFIG_BT_NIMBLE_MSYS_1_BLOCK_SIZE 256
#define CONFIG_BT_NIMBLE_MSYS_2_BLOCK_COUNT 24
#define CONFIG_BT_NIMBLE_MSYS_2_BLOCK_SIZE 320
#define CONFIG_BT_NIMBLE_ACL_BUF_COUNT 24
#define CONFIG_BT_NIMBLE_ACL_BUF_SIZE 255
#define CONFIG_BT_NIMBLE_HCI_EVT_BUF_SIZE 70
#define CONFIG_BT_NIMBLE_HCI_EVT_HI_BUF_COUNT 30
#define CONFIG_BT_NIMBLE_HCI_EVT_LO_BUF_COUNT 8
#define CONFIG_BT_NIMBLE_GATT_MAX_PROCS 4
#define CONFIG_BT_NIMBLE_RPA_TIMEOUT 900
#define CONFIG_BT_NIMBLE_CRYPTO_STACK_MBEDTLS 1
#define CONFIG_BT_NIMBLE_HS_STOP_TIMEOUT_MS 2000
#define CONFIG_BT_NIMBLE_ENABLE_CONN_REATTEMPT 1
#define CONFIG_BT_NIMBLE_MAX_CONN_REATTEMPT 3
#define CONFIG_BT_NIMBLE_50_FEATURE_SUPPORT 1
#define CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_2M_PHY 1
#define CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_CODED_PHY 1
#define CONFIG_BT_NIMBLE_MAX_PERIODIC_SYNCS 0
#define CONFIG_BT_NIMBLE_WHITELIST_SIZE 12
#define CONFIG_BT_NIMBLE_USE_ESP_TIMER 1
#define CONFIG_BT_NIMBLE_LEGACY_VHCI_ENABLE 1
#define CONFIG_BT_CTRL_MODE_EFF 1
#define CONFIG_BT_CTRL_BLE_MAX_ACT 6
#define CONFIG_BT_CTRL_BLE_MAX_ACT_EFF 6
#define CONFIG_BT_CTRL_BLE_STATIC_ACL_TX_BUF_NB 0
#define CONFIG_BT_CTRL_PINNED_TO_CORE 0
#define CONFIG_BT_CTRL_HCI_MODE_VHCI 1
#define CONFIG_BT_CTRL_HCI_TL 1
#define CONFIG_BT_CTRL_ADV_DUP_FILT_MAX 30
#define CONFIG_BT_CTRL_HW_CCA_VAL 20
#define CONFIG_BT_CTRL_HW_CCA_EFF 0
#define CONFIG_BT_CTRL_CE_LENGTH_TYPE_ORIG 1
#define CONFIG_BT_CTRL_CE_LENGTH_TYPE_EFF 0
#define CONFIG_BT_CTRL_TX_ANTENNA_INDEX_0 1
#define CONFIG_BT_CTRL_TX_ANTENNA_INDEX_EFF 0
#define CONFIG_BT_CTRL_RX_ANTENNA_INDEX_0 1
#define CONFIG_BT_CTRL_RX_ANTENNA_INDEX_EFF 0
#define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_P9 1

#define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_EFF 11
#define CONFIG_BT_CTRL_BLE_ADV_REPORT_FLOW_CTRL_SUPP 1
#define CONFIG_BT_CTRL_BLE_ADV_REPORT_FLOW_CTRL_NUM 100
#define CONFIG_BT_CTRL_BLE_ADV_REPORT_DISCARD_THRSHOLD 20
#define CONFIG_BT_CTRL_BLE_SCAN_DUPL 1
#define CONFIG_BT_CTRL_SCAN_DUPL_TYPE_DEVICE 1
#define CONFIG_BT_CTRL_SCAN_DUPL_TYPE 0
#define CONFIG_BT_CTRL_SCAN_DUPL_CACHE_SIZE 100
#define CONFIG_BT_CTRL_DUPL_SCAN_CACHE_REFRESH_PERIOD 0
#define CONFIG_BT_CTRL_COEX_PHY_CODED_TX_RX_TLIM_DIS 1
#define CONFIG_BT_CTRL_COEX_PHY_CODED_TX_RX_TLIM_EFF 0
#define CONFIG_BT_CTRL_SLEEP_MODE_EFF 0
#define CONFIG_BT_CTRL_SLEEP_CLOCK_EFF 0
#define CONFIG_BT_CTRL_HCI_TL_EFF 1
#define CONFIG_BT_CTRL_CHAN_ASS_EN 1
#define CONFIG_BT_CTRL_LE_PING_EN 1
#define CONFIG_BT_ALARM_MAX_NUM 50
#define CONFIG_MBEDTLS_CMAC_C 1
#define CONFIG_WIFI_PROV_BLE_SEC_CONN 1
#define CONFIG_MAC_BB_PD 0
#endif

#if defined(CONFIG_ESPRESSIF_BLE) && defined(CONFIG_ESPRESSIF_WIFI)
#define CONFIG_ESP_COEX_SW_COEXIST_ENABLE 1
#endif

#define CONFIG_MBEDTLS_ASYMMETRIC_CONTENT_LEN 1
#define CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN 16384
#define CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN 4096
#define CONFIG_MBEDTLS_SSL_KEEP_PEER_CERTIFICATE 1
#define CONFIG_MBEDTLS_PKCS7_C 1
#define CONFIG_MBEDTLS_AES_USE_INTERRUPT 1
#define CONFIG_MBEDTLS_MPI_USE_INTERRUPT 1
#define CONFIG_MBEDTLS_ROM_MD5 1
#define CONFIG_MBEDTLS_HAVE_TIME 1
#define CONFIG_MBEDTLS_ECDSA_DETERMINISTIC 1
#define CONFIG_MBEDTLS_SHA1_C 1
#define CONFIG_MBEDTLS_SHA512_C 1
#define CONFIG_MBEDTLS_TLS_SERVER_AND_CLIENT 1
#define CONFIG_MBEDTLS_TLS_SERVER 1
#define CONFIG_MBEDTLS_TLS_CLIENT 1
#define CONFIG_MBEDTLS_TLS_ENABLED 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_RSA 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ELLIPTIC_CURVE 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_RSA 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_RSA 1
#define CONFIG_MBEDTLS_SSL_RENEGOTIATION 1
#define CONFIG_MBEDTLS_SSL_PROTO_TLS1_2 1
#define CONFIG_MBEDTLS_SSL_ALPN 1
#define CONFIG_MBEDTLS_CLIENT_SSL_SESSION_TICKETS 1
#define CONFIG_MBEDTLS_SERVER_SSL_SESSION_TICKETS 1
#define CONFIG_MBEDTLS_AES_C 1
#define CONFIG_MBEDTLS_CCM_C 1
#define CONFIG_MBEDTLS_GCM_C 1
#define CONFIG_MBEDTLS_PEM_PARSE_C 1
#define CONFIG_MBEDTLS_PEM_WRITE_C 1
#define CONFIG_MBEDTLS_X509_CRL_PARSE_C 1
#define CONFIG_MBEDTLS_X509_CSR_PARSE_C 1
#define CONFIG_MBEDTLS_ECP_C 1
#define CONFIG_MBEDTLS_ECDH_C 1
#define CONFIG_MBEDTLS_ECDSA_C 1
#define CONFIG_MBEDTLS_ECP_DP_SECP192R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP224R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP384R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP521R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP192K1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP224K1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP256K1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_BP256R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_BP384R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_BP512R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_CURVE25519_ENABLED 1
#define CONFIG_MBEDTLS_ECP_NIST_OPTIM 1
#define CONFIG_MBEDTLS_ECP_FIXED_POINT_OPTIM 1
#define CONFIG_MBEDTLS_LARGE_KEY_SOFTWARE_MPI 1

#ifdef CONFIG_ESPRESSIF_WIFI
#define CONFIG_ESP_WIFI_ENABLED 1
#define CONFIG_ESP_WIFI_TX_BUFFER_TYPE 1
#define CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM CONFIG_ESPRESSIF_WIFI_STATIC_RX_BUFFER_NUM
#define CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM CONFIG_ESPRESSIF_WIFI_DYNAMIC_RX_BUFFER_NUM
#define CONFIG_ESP_WIFI_STATIC_RX_MGMT_BUFFER 1
#define CONFIG_ESP_WIFI_DYNAMIC_RX_MGMT_BUF 0
#define CONFIG_ESP_WIFI_RX_MGMT_BUF_NUM_DEF 5
#define CONFIG_ESP_WIFI_AMPDU_TX_ENABLED CONFIG_ESPRESSIF_WIFI_AMPDU_TX_ENABLED
#define CONFIG_ESP_WIFI_TX_BA_WIN CONFIG_ESPRESSIF_WIFI_TX_BA_WIN
#define CONFIG_ESP_WIFI_AMPDU_RX_ENABLED CONFIG_ESPRESSIF_WIFI_AMPDU_RX_ENABLED
#define CONFIG_ESP_WIFI_RX_BA_WIN CONFIG_ESPRESSIF_WIFI_RX_BA_WIN
#define CONFIG_ESP_WIFI_SOFTAP_BEACON_MAX_LEN 752
#define CONFIG_ESP_WIFI_MGMT_SBUF_NUM 32
#define CONFIG_ESP_WIFI_IRAM_OPT 1
#define CONFIG_ESP_WIFI_RX_IRAM_OPT 1
#define CONFIG_ESP_WIFI_ENABLE_WPA3_SAE CONFIG_ESPRESSIF_WIFI_ENABLE_WPA3_SAE
#define CONFIG_ESP_WIFI_ENABLE_SAE_PK CONFIG_ESPRESSIF_WIFI_ENABLE_SAE_PK
#define CONFIG_ESP_WIFI_ENABLE_SAE_H2E CONFIG_ESPRESSIF_WIFI_ENABLE_SAE_H2E
#define CONFIG_ESP_WIFI_SOFTAP_SAE_SUPPORT CONFIG_ESPRESSIF_WIFI_SOFTAP_SAE_SUPPORT
#define CONFIG_ESP_WIFI_ENABLE_WPA3_OWE_STA CONFIG_ESPRESSIF_WIFI_ENABLE_WPA3_OWE_STA
#define CONFIG_ESP_WIFI_SLP_DEFAULT_MIN_ACTIVE_TIME 50
#define CONFIG_ESP_WIFI_SLP_DEFAULT_MAX_ACTIVE_TIME 10
#define CONFIG_ESP_WIFI_SLP_DEFAULT_WAIT_BROADCAST_DATA_TIME 15
#define CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE CONFIG_ESPRESSIF_WIFI_STA_DISCONNECT_PM
#define CONFIG_ESP_WIFI_GMAC_SUPPORT 1
#define CONFIG_ESP_WIFI_SOFTAP_SUPPORT 1
#define CONFIG_ESP_WIFI_ESPNOW_MAX_ENCRYPT_NUM 7
#define CONFIG_ESP_WIFI_MBEDTLS_CRYPTO 1
#define CONFIG_ESP_WIFI_MBEDTLS_TLS_CLIENT 1
#define CONFIG_ESP_WIFI_WAPI_PSK CONFIG_WPA_WAPI_PSK
#endif

#define CONFIG_ESP_REV_MIN_FULL 3
#define CONFIG_ESP_REV_MAX_FULL 99
#define CONFIG_IDF_TARGET_ARCH_RISCV 1
#define CONFIG_IDF_TARGET_ARCH "riscv"
#define CONFIG_IDF_TARGET "esp32c3"
#define CONFIG_IDF_TARGET_ESP32C3 1
#define CONFIG_IDF_FIRMWARE_CHIP_ID 0x0005
#define CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ CONFIG_ESPRESSIF_CPU_FREQ_MHZ
#define CONFIG_RTC_CLK_SRC_INT_RC 1
#define CONFIG_RTC_CLK_CAL_CYCLES 1024
#define CONFIG_XTAL_FREQ 40

#define CONFIG_BOOTLOADER_LOG_VERSION_1 1
#define CONFIG_BOOTLOADER_LOG_VERSION 1
#define CONFIG_BOOTLOADER_LOG_LEVEL_INFO 1
#define CONFIG_BOOTLOADER_LOG_LEVEL 3

#define CONFIG_MMU_PAGE_SIZE 0x10000
#define SOC_MMU_PAGE_SIZE CONFIG_MMU_PAGE_SIZE

#define CONFIG_LOG_TIMESTAMP_SOURCE_RTOS 1

#define CONFIG_IDF_ENV_FPGA 0

#ifdef CONFIG_ESPRESSIF_BROWNOUT_DET
#define CONFIG_ESP_BROWNOUT_DET_LVL CONFIG_ESPRESSIF_BROWNOUT_DET_LVL
#else
#define CONFIG_ESP_BROWNOUT_DET 0
#endif

#if defined(CONFIG_ESPRESSIF_EFUSE_VIRTUAL)
#define CONFIG_EFUSE_VIRTUAL 1
#endif

#if defined(CONFIG_DEBUG_INFO)
#define CONFIG_LOG_DEFAULT_LEVEL 3
#define CONFIG_LOG_MAXIMUM_LEVEL 3
#elif defined(CONFIG_DEBUG_WARN)
#define CONFIG_LOG_DEFAULT_LEVEL 2
#define CONFIG_LOG_MAXIMUM_LEVEL 2
#elif defined(CONFIG_DEBUG_ERROR)
#define CONFIG_LOG_DEFAULT_LEVEL 1
#define CONFIG_LOG_MAXIMUM_LEVEL 1
#else
#define CONFIG_LOG_DEFAULT_LEVEL 0
#define CONFIG_LOG_MAXIMUM_LEVEL 0
#endif

/* SPI Flash related configs */

#if defined(CONFIG_ESPRESSIF_FLASH_MODE_QIO)
#  define CONFIG_ESPTOOLPY_FLASHMODE_QIO 1
#  define CONFIG_ESPTOOLPY_FLASHMODE "dio"
#elif defined(CONFIG_ESPRESSIF_FLASH_MODE_QOUT)
#  define CONFIG_ESPTOOLPY_FLASHMODE_QOUT 1
#  define CONFIG_ESPTOOLPY_FLASHMODE "dio"
#elif defined(CONFIG_ESPRESSIF_FLASH_MODE_DIO)
#  define CONFIG_ESPTOOLPY_FLASHMODE_DIO 1
#  define CONFIG_ESPTOOLPY_FLASHMODE "dio"
#elif defined(CONFIG_ESPRESSIF_FLASH_MODE_DOUT)
#  define CONFIG_ESPTOOLPY_FLASHMODE_DOUT 1
#  define CONFIG_ESPTOOLPY_FLASHMODE "dout"
#endif

#define CONFIG_ESPTOOLPY_FLASH_SAMPLE_MODE_STR 1

#ifdef CONFIG_ESPRESSIF_SPI_FLASH_USE_32BIT_ADDRESS
#  define CONFIG_BOOTLOADER_CACHE_32BIT_ADDR_OCTAL_FLASH 1
#endif

#ifdef CONFIG_ESPRESSIF_SPI_FLASH_USE_ROM_CODE
#  define CONFIG_SPI_FLASH_ROM_IMPL 1
#endif

#if defined(CONFIG_ESPRESSIF_FLASH_FREQ_20M)
#  define CONFIG_ESPTOOLPY_FLASHFREQ_20M 1
#  define CONFIG_ESPTOOLPY_FLASHFREQ_80M_DEFAULT 1
#  define CONFIG_ESPTOOLPY_FLASHFREQ "20m"
#elif defined(CONFIG_ESPRESSIF_FLASH_FREQ_26M)
#  define CONFIG_ESPTOOLPY_FLASHFREQ_26M 1
#  define CONFIG_ESPTOOLPY_FLASHFREQ_26M_DEFAULT 1
#  define CONFIG_ESPTOOLPY_FLASHFREQ "26m"
#elif defined(CONFIG_ESPRESSIF_FLASH_FREQ_40M)
#  define CONFIG_ESPTOOLPY_FLASHFREQ_40M 1
#  define CONFIG_ESPTOOLPY_FLASHFREQ_80M_DEFAULT 1
#  define CONFIG_ESPTOOLPY_FLASHFREQ "40m"
#elif defined(CONFIG_ESPRESSIF_FLASH_FREQ_80M)
#  define CONFIG_ESPTOOLPY_FLASHFREQ_80M 1
#  define CONFIG_ESPTOOLPY_FLASHFREQ_80M_DEFAULT 1
#  define CONFIG_ESPTOOLPY_FLASHFREQ "80m"
#else
#  error "SPI timing flash clock is invalid"
#endif

#if defined(CONFIG_ESPRESSIF_RTC_CLK_EXT_XTAL)
#define CONFIG_RTC_CLK_SRC_EXT_CRYS     1
#elif defined(CONFIG_ESPRESSIF_RTC_CLK_EXT_OSC)
#define CONFIG_RTC_CLK_SRC_EXT_OSC      1
#elif defined(CONFIG_ESPRESSIF_RTC_CLK_INT_8MD256)
#define CONFIG_RTC_CLK_SRC_INT_8MD256   1
#endif

/* UART Console Settings */

#if (defined(CONFIG_UART0_SERIAL_CONSOLE) && defined(CONFIG_ESPRESSIF_UART0)) || defined(CONFIG_ESPRESSIF_USBSERIAL)
#  define CONFIG_ESP_CONSOLE_UART_NUM            0
#  define CONFIG_ESP_CONSOLE_UART_DEFAULT        1
#  define CONFIG_ESP_CONSOLE_ROM_SERIAL_PORT_NUM 0
#elif defined(CONFIG_UART1_SERIAL_CONSOLE) && defined(CONFIG_ESPRESSIF_UART1)
#  define CONFIG_ESP_CONSOLE_UART_NUM            1
#  define CONFIG_ESP_CONSOLE_ROM_SERIAL_PORT_NUM 1
#  define CONFIG_ESP_CONSOLE_UART_CUSTOM         1
#  define CONFIG_ESP_CONSOLE_UART_CUSTOM_NUM_1   1
#  define CONFIG_ESP_CONSOLE_UART_TX_GPIO        CONFIG_ESPRESSIF_UART1_TXPIN
#  define CONFIG_ESP_CONSOLE_UART_RX_GPIO        CONFIG_ESPRESSIF_UART1_RXPIN
#endif

#if defined (CONFIG_ESPRESSIF_SIMPLE_BOOT) || \
    defined (CONFIG_ESPRESSIF_BOOTLOADER_MCUBOOT)
#  define CONFIG_ESP_CONSOLE_UART 1
#  define CONFIG_ESP_CONSOLE_UART_BAUDRATE 115200
#  define CONFIG_PARTITION_TABLE_OFFSET 0x0000
#  define CONFIG_BOOTLOADER_OFFSET_IN_FLASH 0x0000
#  define IDF_VER 0
#  define CONFIG_FREERTOS_UNICORE 1
#  define CONFIG_BOOTLOADER_FLASH_XMC_SUPPORT 1
#endif

/* List of deprecated options */

#define CONFIG_CONSOLE_UART                                 CONFIG_ESP_CONSOLE_UART
#define CONFIG_CONSOLE_UART_DEFAULT                         CONFIG_ESP_CONSOLE_UART_DEFAULT
#define CONFIG_CONSOLE_UART_CUSTOM                          CONFIG_ESP_CONSOLE_UART_CUSTOM
#define CONFIG_CONSOLE_UART_NONE                            CONFIG_ESP_CONSOLE_NONE
#define CONFIG_ESP_CONSOLE_UART_NONE                        CONFIG_ESP_CONSOLE_NONE
#define CONFIG_CONSOLE_UART_NUM                             CONFIG_ESP_CONSOLE_UART_NUM
#define CONFIG_CONSOLE_UART_CUSTOM_NUM_0                    CONFIG_ESP_CONSOLE_UART_CUSTOM_NUM_0
#define CONFIG_CONSOLE_UART_CUSTOM_NUM_1                    CONFIG_ESP_CONSOLE_UART_CUSTOM_NUM_1
#define CONFIG_CONSOLE_UART_TX_GPIO                         CONFIG_ESP_CONSOLE_UART_TX_GPIO
#define CONFIG_CONSOLE_UART_RX_GPIO                         CONFIG_ESP_CONSOLE_UART_RX_GPIO
#define CONFIG_CONSOLE_UART_BAUDRATE                        CONFIG_ESP_CONSOLE_UART_BAUDRATE
#define CONFIG_OPTIMIZATION_LEVEL_DEBUG                     CONFIG_COMPILER_OPTIMIZATION_DEBUG
#define CONFIG_ADC2_DISABLE_DAC                             CONFIG_ADC_DISABLE_DAC
#define CONFIG_MCPWM_ISR_IN_IRAM                            CONFIG_MCPWM_ISR_IRAM_SAFE
#define CONFIG_ESP32_RTC_XTAL_BOOTSTRAP_CYCLES              CONFIG_ESP_SYSTEM_RTC_EXT_XTAL_BOOTSTRAP_CYCLES
#define CONFIG_SYSTEM_EVENT_QUEUE_SIZE                      CONFIG_ESP_SYSTEM_EVENT_QUEUE_SIZE
#define CONFIG_SYSTEM_EVENT_TASK_STACK_SIZE                 CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE
#define CONFIG_MAIN_TASK_STACK_SIZE                         CONFIG_ESP_MAIN_TASK_STACK_SIZE
#define CONFIG_IPC_TASK_STACK_SIZE                          CONFIG_ESP_IPC_TASK_STACK_SIZE
#define CONFIG_INT_WDT                                      CONFIG_ESP_INT_WDT
#define CONFIG_INT_WDT_TIMEOUT_MS                           CONFIG_ESP_INT_WDT_TIMEOUT_MS
#define CONFIG_INT_WDT_CHECK_CPU1                           CONFIG_ESP_INT_WDT_CHECK_CPU1
#define CONFIG_TASK_WDT                                     CONFIG_ESP_TASK_WDT_INIT
#define CONFIG_TASK_WDT_PANIC                               CONFIG_ESP_TASK_WDT_PANIC
#define CONFIG_TASK_WDT_TIMEOUT_S                           CONFIG_ESP_TASK_WDT_TIMEOUT_S
#define CONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU0                CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0
#define CONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU1                CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1
#define CONFIG_ESP_TASK_WDT                                 CONFIG_ESP_TASK_WDT_INIT
#define CONFIG_ESP32_DEBUG_STUBS_ENABLE                     CONFIG_ESP_DEBUG_STUBS_ENABLE
#define CONFIG_ESP32C3_MEMPROT_FEATURE                      CONFIG_ESP_SYSTEM_MEMPROT_FEATURE
#define CONFIG_ESP32C3_MEMPROT_FEATURE_LOCK                 CONFIG_ESP_SYSTEM_MEMPROT_FEATURE_LOCK
#define CONFIG_ESP32C3_DEBUG_OCDAWARE                       CONFIG_ESP_DEBUG_OCDAWARE
#define CONFIG_ESP32C3_BROWNOUT_DET                         CONFIG_ESP_BROWNOUT_DET
#define CONFIG_ESP32C3_BROWNOUT_DET_LVL_SEL                 CONFIG_ESP_BROWNOUT_DET_LVL_SEL
#define CONFIG_ESP32C3_BROWNOUT_DET_LVL_SEL_0               CONFIG_ESP_BROWNOUT_DET_LVL_SEL_0
#define CONFIG_ESP32C3_BROWNOUT_DET_LVL_SEL_1               CONFIG_ESP_BROWNOUT_DET_LVL_SEL_1
#define CONFIG_ESP32C3_BROWNOUT_DET_LVL_SEL_2               CONFIG_ESP_BROWNOUT_DET_LVL_SEL_2
#define CONFIG_ESP32C3_BROWNOUT_DET_LVL_SEL_3               CONFIG_ESP_BROWNOUT_DET_LVL_SEL_3
#define CONFIG_ESP32C3_BROWNOUT_DET_LVL_SEL_4               CONFIG_ESP_BROWNOUT_DET_LVL_SEL_4
#define CONFIG_ESP32C3_BROWNOUT_DET_LVL_SEL_5               CONFIG_ESP_BROWNOUT_DET_LVL_SEL_5
#define CONFIG_ESP32C3_BROWNOUT_DET_LVL_SEL_6               CONFIG_ESP_BROWNOUT_DET_LVL_SEL_6
#define CONFIG_ESP32C3_BROWNOUT_DET_LVL_SEL_7               CONFIG_ESP_BROWNOUT_DET_LVL_SEL_7
#define CONFIG_ESP32C3_BROWNOUT_DET_LVL                     CONFIG_ESP_BROWNOUT_DET_LVL
#define CONFIG_ESP32C3_DEFAULT_CPU_FREQ_MHZ                 CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ
#define CONFIG_ESP32C3_DEFAULT_CPU_FREQ_40                  CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_40
#define CONFIG_ESP32C3_DEFAULT_CPU_FREQ_80                  CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_80
#define CONFIG_ESP32C3_DEFAULT_CPU_FREQ_160                 CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_160
#define CONFIG_BT_NIMBLE_COEX_PHY_CODED_TX_RX_TLIM_EN       CONFIG_BT_CTRL_COEX_PHY_CODED_TX_RX_TLIM_EN
#define CONFIG_BT_NIMBLE_COEX_PHY_CODED_TX_RX_TLIM_DIS      CONFIG_BT_CTRL_COEX_PHY_CODED_TX_RX_TLIM_DIS
#define CONFIG_REDUCE_PHY_TX_POWER                          CONFIG_ESP_PHY_REDUCE_TX_POWER
#define CONFIG_ESP32_PHY_MAC_BB_PD                          CONFIG_ESP_PHY_MAC_BB_PD
#define CONFIG_ESP32_REDUCE_PHY_TX_POWER                    CONFIG_ESP_PHY_REDUCE_TX_POWER
#define CONFIG_ESP32_PHY_CALIBRATION_AND_DATA_STORAGE       CONFIG_ESP_PHY_CALIBRATION_AND_DATA_STORAGE
#define CONFIG_ESP32_PHY_INIT_DATA_IN_PARTITION             CONFIG_ESP_PHY_INIT_DATA_IN_PARTITION
#define CONFIG_ESP32_PHY_DEFAULT_INIT_IF_INVALID            CONFIG_ESP_PHY_DEFAULT_INIT_IF_INVALID
#define CONFIG_ESP32_SUPPORT_MULTIPLE_PHY_INIT_DATA_BIN     CONFIG_ESP_PHY_MULTIPLE_INIT_DATA_BIN
#define CONFIG_ESP32_PHY_INIT_DATA_ERROR                    CONFIG_ESP_PHY_INIT_DATA_ERROR
#define CONFIG_ESP32_PHY_MAX_WIFI_TX_POWER                  CONFIG_ESP_PHY_MAX_WIFI_TX_POWER
#define CONFIG_ESP32_PHY_MAX_TX_POWER                       CONFIG_ESP_PHY_MAX_TX_POWER
#define CONFIG_ENABLE_STATIC_TASK_CLEAN_UP_HOOK             CONFIG_FREERTOS_ENABLE_STATIC_TASK_CLEAN_UP
#define CONFIG_TIMER_TASK_PRIORITY                          CONFIG_FREERTOS_TIMER_TASK_PRIORITY
#define CONFIG_TIMER_TASK_STACK_DEPTH                       CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH
#define CONFIG_TIMER_QUEUE_LENGTH                           CONFIG_FREERTOS_TIMER_QUEUE_LENGTH
#define CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY           CONFIG_FREERTOS_TASK_CREATE_ALLOW_EXT_MEM
#define CONFIG_ESP32_PTHREAD_TASK_PRIO_DEFAULT              CONFIG_PTHREAD_TASK_PRIO_DEFAULT
#define CONFIG_ESP32_PTHREAD_TASK_STACK_SIZE_DEFAULT        CONFIG_PTHREAD_TASK_STACK_SIZE_DEFAULT
#define CONFIG_ESP32_PTHREAD_STACK_MIN                      CONFIG_PTHREAD_STACK_MIN
#define CONFIG_ESP32_PTHREAD_TASK_CORE_DEFAULT              CONFIG_PTHREAD_TASK_CORE_DEFAULT
#define CONFIG_ESP32_DEFAULT_PTHREAD_CORE_NO_AFFINITY       CONFIG_PTHREAD_DEFAULT_CORE_NO_AFFINITY
#define CONFIG_ESP32_DEFAULT_PTHREAD_CORE_0                 CONFIG_PTHREAD_DEFAULT_CORE_0
#define CONFIG_ESP32_DEFAULT_PTHREAD_CORE_1                 CONFIG_PTHREAD_DEFAULT_CORE_1
#define CONFIG_ESP32_PTHREAD_TASK_NAME_DEFAULT              CONFIG_PTHREAD_TASK_NAME_DEFAULT
#define CONFIG_TIMER_TASK_STACK_SIZE                        CONFIG_ESP_TIMER_TASK_STACK_SIZE
#define CONFIG_ESP_SYSTEM_PM_POWER_DOWN_CPU                 CONFIG_PM_POWER_DOWN_CPU_IN_LIGHT_SLEEP
#define CONFIG_PM_POWER_DOWN_TAGMEM_IN_LIGHT_SLEEP          CONFIG_PM_RESTORE_CACHE_TAGMEM_AFTER_LIGHT_SLEEP
#define CONFIG_EVENT_LOOP_PROFILING                         CONFIG_ESP_EVENT_LOOP_PROFILING
#define CONFIG_POST_EVENTS_FROM_ISR                         CONFIG_ESP_EVENT_POST_FROM_ISR
#define CONFIG_POST_EVENTS_FROM_IRAM_ISR                    CONFIG_ESP_EVENT_POST_FROM_IRAM_ISR
#define CONFIG_ESP32_APPTRACE_DESTINATION                   CONFIG_APPTRACE_DESTINATION
#define CONFIG_ESP32_APPTRACE_DEST_NONE                     CONFIG_APPTRACE_DEST_NONE
#define CONFIG_ESP32_APPTRACE_DEST_TRAX                     CONFIG_APPTRACE_DEST_JTAG
#define CONFIG_ESP32_APPTRACE_ENABLE                        CONFIG_APPTRACE_ENABLE
#define CONFIG_ESP32_APPTRACE_LOCK_ENABLE                   CONFIG_APPTRACE_LOCK_ENABLE
#define CONFIG_ESP32_APPTRACE_ONPANIC_HOST_FLUSH_TMO        CONFIG_APPTRACE_ONPANIC_HOST_FLUSH_TMO
#define CONFIG_ESP32_APPTRACE_POSTMORTEM_FLUSH_TRAX_THRESH  CONFIG_APPTRACE_POSTMORTEM_FLUSH_THRESH
#define CONFIG_ESP32_APPTRACE_PENDING_DATA_SIZE_MAX		    CONFIG_APPTRACE_PENDING_DATA_SIZE_MAX
#define CONFIG_ESP32_GCOV_ENABLE						    CONFIG_APPTRACE_GCOV_ENABLE
#define CONFIG_OTA_ALLOW_HTTP                               CONFIG_ESP_HTTPS_OTA_ALLOW_HTTP
#define CONFIG_SEMIHOSTFS_HOST_PATH_MAX_LEN                 CONFIG_VFS_SEMIHOSTFS_HOST_PATH_MAX_LEN
#define CONFIG_SEMIHOSTFS_MAX_MOUNT_POINTS                  CONFIG_VFS_SEMIHOSTFS_MAX_MOUNT_POINTS
#define CONFIG_SUPPORT_TERMIOS                              CONFIG_VFS_SUPPORT_TERMIOS
#define CONFIG_SUPPRESS_SELECT_DEBUG_OUTPUT                 CONFIG_VFS_SUPPRESS_SELECT_DEBUG_OUTPUT
#define CONFIG_ESP32_ENABLE_COREDUMP_TO_FLASH               CONFIG_ESP_COREDUMP_ENABLE_TO_FLASH
#define CONFIG_ESP32_ENABLE_COREDUMP_TO_UART                CONFIG_ESP_COREDUMP_ENABLE_TO_UART
#define CONFIG_ESP32_ENABLE_COREDUMP_TO_NONE                CONFIG_ESP_COREDUMP_ENABLE_TO_NONE
#define CONFIG_ESP32_COREDUMP_DATA_FORMAT_BIN               CONFIG_ESP_COREDUMP_DATA_FORMAT_BIN
#define CONFIG_ESP32_COREDUMP_DATA_FORMAT_ELF               CONFIG_ESP_COREDUMP_DATA_FORMAT_ELF
#define CONFIG_ESP32_COREDUMP_CHECKSUM_CRC32                CONFIG_ESP_COREDUMP_CHECKSUM_CRC32
#define CONFIG_ESP32_COREDUMP_CHECKSUM_SHA256               CONFIG_ESP_COREDUMP_CHECKSUM_SHA256
#define CONFIG_ESP32_ENABLE_COREDUMP                        CONFIG_ESP_COREDUMP_ENABLE
#define CONFIG_ESP32_CORE_DUMP_MAX_TASKS_NUM                CONFIG_ESP_COREDUMP_MAX_TASKS_NUM
#define CONFIG_ESP32_CORE_DUMP_UART_DELAY                   CONFIG_ESP_COREDUMP_UART_DELAY
#define CONFIG_ESP32_CORE_DUMP_STACK_SIZE                   CONFIG_ESP_COREDUMP_STACK_SIZE
#define CONFIG_ESP32_CORE_DUMP_DECODE_INFO                  CONFIG_ESP_COREDUMP_DECODE_INFO
#define CONFIG_ESP32_CORE_DUMP_DECODE_DISABLE               CONFIG_ESP_COREDUMP_DECODE_DISABLE
#define CONFIG_ESP32_CORE_DUMP_DECODE                       CONFIG_ESP_COREDUMP_DECODE
#define CONFIG_LOG_BOOTLOADER_LEVEL                         CONFIG_BOOTLOADER_LOG_LEVEL
#define CONFIG_LOG_BOOTLOADER_LEVEL_NONE                    CONFIG_BOOTLOADER_LOG_LEVEL_NONE
#define CONFIG_LOG_BOOTLOADER_LEVEL_ERROR                   CONFIG_BOOTLOADER_LOG_LEVEL_ERROR
#define CONFIG_LOG_BOOTLOADER_LEVEL_WARN                    CONFIG_BOOTLOADER_LOG_LEVEL_WARN
#define CONFIG_LOG_BOOTLOADER_LEVEL_INFO                    CONFIG_BOOTLOADER_LOG_LEVEL_INFO
#define CONFIG_LOG_BOOTLOADER_LEVEL_DEBUG                   CONFIG_BOOTLOADER_LOG_LEVEL_DEBUG
#define CONFIG_LOG_BOOTLOADER_LEVEL_VERBOSE                 CONFIG_BOOTLOADER_LOG_LEVEL_VERBOSE
#define CONFIG_APP_ROLLBACK_ENABLE                          CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE
#define CONFIG_APP_ANTI_ROLLBACK                            CONFIG_BOOTLOADER_APP_ANTI_ROLLBACK
#define CONFIG_APP_SECURE_VERSION                           CONFIG_BOOTLOADER_APP_SECURE_VERSION
#define CONFIG_APP_SECURE_VERSION_SIZE_EFUSE_FIELD          CONFIG_BOOTLOADER_APP_SEC_VER_SIZE_EFUSE_FIELD
#define CONFIG_EFUSE_SECURE_VERSION_EMULATE                 CONFIG_BOOTLOADER_EFUSE_SECURE_VERSION_EMULATE
#define CONFIG_FLASH_ENCRYPTION_ENABLED                     CONFIG_SECURE_FLASH_ENC_ENABLED
#define CONFIG_FLASH_ENCRYPTION_INSECURE                    CONFIG_SECURE_FLASH_ENCRYPTION_MODE_DEVELOPMENT
#define CONFIG_FLASH_ENCRYPTION_UART_BOOTLOADER_ALLOW_ENCRYPT   CONFIG_SECURE_FLASH_UART_BOOTLOADER_ALLOW_ENC
#define CONFIG_FLASH_ENCRYPTION_UART_BOOTLOADER_ALLOW_DECRYPT   CONFIG_SECURE_FLASH_UART_BOOTLOADER_ALLOW_DEC
#define CONFIG_FLASH_ENCRYPTION_UART_BOOTLOADER_ALLOW_CACHE     CONFIG_SECURE_FLASH_UART_BOOTLOADER_ALLOW_CACHE
#define CONFIG_SECURE_BOOT_ENABLED                          CONFIG_SECURE_BOOT_V1_ENABLED
#define CONFIG_SPI_FLASH_32BIT_ADDR_ENABLE                  CONFIG_BOOTLOADER_CACHE_32BIT_ADDR_QUAD_FLASH
#define CONFIG_SPI_FLASH_QUAD_32BIT_ADDR_ENABLE             CONFIG_BOOTLOADER_CACHE_32BIT_ADDR_QUAD_FLASH
#define CONFIG_SPI_FLASH_OCTAL_32BIT_ADDR_ENABLE            CONFIG_BOOTLOADER_CACHE_32BIT_ADDR_OCTAL_FLASH
#define CONFIG_NUMBER_OF_UNIVERSAL_MAC_ADDRESS              CONFIG_ESP32_UNIVERSAL_MAC_ADDRESSES
#define CONFIG_TWO_UNIVERSAL_MAC_ADDRESS                    CONFIG_ESP32_UNIVERSAL_MAC_ADDRESSES_TWO
#define CONFIG_FOUR_UNIVERSAL_MAC_ADDRESS                   CONFIG_ESP32_UNIVERSAL_MAC_ADDRESSES_FOUR
#define CONFIG_ESP_SYSTEM_PD_FLASH                          CONFIG_ESP_SLEEP_POWER_DOWN_FLASH
#define CONFIG_ESP_SYSTEM_BROWNOUT_INTR                     CONFIG_ESP_BROWNOUT_USE_INTR
#define CONFIG_PERIPH_CTRL_FUNC_IN_IRAM                     CONFIG_ESP_PERIPH_CTRL_FUNC_IN_IRAM
#define CONFIG_NEWLIB_STDOUT_LINE_ENDING                    CONFIG_LIBC_STDOUT_LINE_ENDING
#define CONFIG_NEWLIB_STDOUT_LINE_ENDING_CRLF               CONFIG_LIBC_STDOUT_LINE_ENDING_CRLF
#define CONFIG_NEWLIB_STDOUT_LINE_ENDING_LF                 CONFIG_LIBC_STDOUT_LINE_ENDING_LF
#define CONFIG_NEWLIB_STDOUT_LINE_ENDING_CR                 CONFIG_LIBC_STDOUT_LINE_ENDING_CR
#define CONFIG_NEWLIB_STDIN_LINE_ENDING                     CONFIG_LIBC_STDIN_LINE_ENDING
#define CONFIG_NEWLIB_STDIN_LINE_ENDING_CRLF                CONFIG_LIBC_STDIN_LINE_ENDING_CRLF
#define CONFIG_NEWLIB_STDIN_LINE_ENDING_LF                  CONFIG_LIBC_STDIN_LINE_ENDING_LF
#define CONFIG_NEWLIB_STDIN_LINE_ENDING_CR                  CONFIG_LIBC_STDIN_LINE_ENDING_CR
#define CONFIG_NEWLIB_NANO_FORMAT                           CONFIG_LIBC_NEWLIB_NANO_FORMAT
#define CONFIG_NEWLIB_TIME_SYSCALL                          CONFIG_LIBC_TIME_SYSCALL
#define CONFIG_NEWLIB_TIME_SYSCALL_USE_RTC_HRT              CONFIG_LIBC_TIME_SYSCALL_USE_RTC_HRT
#define CONFIG_NEWLIB_TIME_SYSCALL_USE_RTC                  CONFIG_LIBC_TIME_SYSCALL_USE_RTC
#define CONFIG_NEWLIB_TIME_SYSCALL_USE_HRT                  CONFIG_LIBC_TIME_SYSCALL_USE_HRT
#define CONFIG_NEWLIB_TIME_SYSCALL_USE_NONE                 CONFIG_LIBC_TIME_SYSCALL_USE_NONE
#define CONFIG_HAL_ASSERTION_SILIENT                        CONFIG_HAL_ASSERTION_SILENT
#define CONFIG_GDBSTUB_SUPPORT_TASKS                        CONFIG_ESP_GDBSTUB_SUPPORT_TASKS
#define CONFIG_GDBSTUB_MAX_TASKS                            CONFIG_ESP_GDBSTUB_MAX_TASKS
#define CONFIG_FLASHMODE_QIO                                CONFIG_ESPTOOLPY_FLASHMODE_QIO
#define CONFIG_FLASHMODE_QOUT                               CONFIG_ESPTOOLPY_FLASHMODE_QOUT
#define CONFIG_FLASHMODE_DIO                                CONFIG_ESPTOOLPY_FLASHMODE_DIO
#define CONFIG_FLASHMODE_DOUT                               CONFIG_ESPTOOLPY_FLASHMODE_DOUT
#define CONFIG_MONITOR_BAUD                                 CONFIG_ESPTOOLPY_MONITOR_BAUD
#define CONFIG_L2_TO_L3_COPY                                CONFIG_LWIP_L2_TO_L3_COPY
#define CONFIG_ESP_GRATUITOUS_ARP                           CONFIG_LWIP_ESP_GRATUITOUS_ARP
#define CONFIG_GARP_TMR_INTERVAL                            CONFIG_LWIP_GARP_TMR_INTERVAL
#define CONFIG_TCPIP_RECVMBOX_SIZE                          CONFIG_LWIP_TCPIP_RECVMBOX_SIZE
#define CONFIG_TCP_MAXRTX                                   CONFIG_LWIP_TCP_MAXRTX
#define CONFIG_TCP_SYNMAXRTX                                CONFIG_LWIP_TCP_SYNMAXRTX
#define CONFIG_TCP_MSS                                      CONFIG_LWIP_TCP_MSS
#define CONFIG_TCP_MSL                                      CONFIG_LWIP_TCP_MSL
#define CONFIG_TCP_SND_BUF_DEFAULT                          CONFIG_LWIP_TCP_SND_BUF_DEFAULT
#define CONFIG_TCP_WND_DEFAULT                              CONFIG_LWIP_TCP_WND_DEFAULT
#define CONFIG_TCP_RECVMBOX_SIZE                            CONFIG_LWIP_TCP_RECVMBOX_SIZE
#define CONFIG_TCP_QUEUE_OOSEQ                              CONFIG_LWIP_TCP_QUEUE_OOSEQ
#define CONFIG_TCP_OVERSIZE                                 CONFIG_LWIP_TCP_OVERSIZE
#define CONFIG_TCP_OVERSIZE_MSS                             CONFIG_LWIP_TCP_OVERSIZE_MSS
#define CONFIG_TCP_OVERSIZE_QUARTER_MSS                     CONFIG_LWIP_TCP_OVERSIZE_QUARTER_MSS
#define CONFIG_TCP_OVERSIZE_DISABLE                         CONFIG_LWIP_TCP_OVERSIZE_DISABLE
#define CONFIG_UDP_RECVMBOX_SIZE                            CONFIG_LWIP_UDP_RECVMBOX_SIZE
#define CONFIG_TCPIP_TASK_STACK_SIZE                        CONFIG_LWIP_TCPIP_TASK_STACK_SIZE
#define CONFIG_TCPIP_TASK_AFFINITY                          CONFIG_LWIP_TCPIP_TASK_AFFINITY
#define CONFIG_TCPIP_TASK_AFFINITY_NO_AFFINITY              CONFIG_LWIP_TCPIP_TASK_AFFINITY_NO_AFFINITY
#define CONFIG_TCPIP_TASK_AFFINITY_CPU0                     CONFIG_LWIP_TCPIP_TASK_AFFINITY_CPU0
#define CONFIG_TCPIP_TASK_AFFINITY_CPU1                     CONFIG_LWIP_TCPIP_TASK_AFFINITY_CPU1
#define CONFIG_PPP_SUPPORT                                  CONFIG_LWIP_PPP_SUPPORT
#define CONFIG_PPP_NOTIFY_PHASE_SUPPORT                     CONFIG_LWIP_PPP_NOTIFY_PHASE_SUPPORT
#define CONFIG_PPP_PAP_SUPPORT                              CONFIG_LWIP_PPP_PAP_SUPPORT
#define CONFIG_PPP_CHAP_SUPPORT                             CONFIG_LWIP_PPP_CHAP_SUPPORT
#define CONFIG_PPP_MSCHAP_SUPPORT                           CONFIG_LWIP_PPP_MSCHAP_SUPPORT
#define CONFIG_PPP_MPPE_SUPPORT                             CONFIG_LWIP_PPP_MPPE_SUPPORT
#define CONFIG_PPP_DEBUG_ON                                 CONFIG_LWIP_PPP_DEBUG_ON
#define CONFIG_SPI_FLASH_WRITING_DANGEROUS_REGIONS          CONFIG_SPI_FLASH_DANGEROUS_WRITE
#define CONFIG_SPI_FLASH_WRITING_DANGEROUS_REGIONS_ABORTS   CONFIG_SPI_FLASH_DANGEROUS_WRITE_ABORTS
#define CONFIG_SPI_FLASH_WRITING_DANGEROUS_REGIONS_FAILS    CONFIG_SPI_FLASH_DANGEROUS_WRITE_FAILS
#define CONFIG_SPI_FLASH_WRITING_DANGEROUS_REGIONS_ALLOWED  CONFIG_SPI_FLASH_DANGEROUS_WRITE_ALLOWED
#define CONFIG_ESP32_WIFI_ENABLED                           CONFIG_ESP_WIFI_ENABLED
#define CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM              CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM
#define CONFIG_ESP32_WIFI_RX_BA_WIN                         CONFIG_ESP_WIFI_RX_BA_WIN
#define CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED                  CONFIG_ESP_WIFI_AMPDU_RX_ENABLED
#define CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM             CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM
#define CONFIG_ESP32_WIFI_TX_BUFFER                         CONFIG_ESP_WIFI_TX_BUFFER
#define CONFIG_ESP32_WIFI_STATIC_TX_BUFFER                  CONFIG_ESP_WIFI_STATIC_TX_BUFFER
#define CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER                 CONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER
#define CONFIG_ESP32_WIFI_TX_BUFFER_TYPE                    CONFIG_ESP_WIFI_TX_BUFFER_TYPE
#define CONFIG_ESP32_WIFI_STATIC_TX_BUFFER_NUM              CONFIG_ESP_WIFI_STATIC_TX_BUFFER_NUM
#define CONFIG_ESP32_WIFI_CACHE_TX_BUFFER_NUM               CONFIG_ESP_WIFI_CACHE_TX_BUFFER_NUM
#define CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER_NUM             CONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER_NUM
#define CONFIG_ESP32_WIFI_CSI_ENABLED                       CONFIG_ESP_WIFI_CSI_ENABLED
#define CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED                  CONFIG_ESP_WIFI_AMPDU_TX_ENABLED
#define CONFIG_ESP32_WIFI_TX_BA_WIN                         CONFIG_ESP_WIFI_TX_BA_WIN
#define CONFIG_ESP32_WIFI_AMSDU_TX_ENABLED                  CONFIG_ESP_WIFI_AMSDU_TX_ENABLED
#define CONFIG_ESP32_WIFI_NVS_ENABLED                       CONFIG_ESP_WIFI_NVS_ENABLED
#define CONFIG_ESP32_WIFI_TASK_CORE_ID                      CONFIG_ESP_WIFI_TASK_CORE_ID
#define CONFIG_ESP32_WIFI_TASK_PINNED_TO_CORE_0             CONFIG_ESP_WIFI_TASK_PINNED_TO_CORE_0
#define CONFIG_ESP32_WIFI_TASK_PINNED_TO_CORE_1             CONFIG_ESP_WIFI_TASK_PINNED_TO_CORE_1
#define CONFIG_ESP32_WIFI_SOFTAP_BEACON_MAX_LEN             CONFIG_ESP_WIFI_SOFTAP_BEACON_MAX_LEN
#define CONFIG_ESP32_WIFI_MGMT_SBUF_NUM                     CONFIG_ESP_WIFI_MGMT_SBUF_NUM
#define CONFIG_ESP32_WIFI_IRAM_OPT                          CONFIG_ESP_WIFI_IRAM_OPT
#define CONFIG_ESP32_WIFI_RX_IRAM_OPT                       CONFIG_ESP_WIFI_RX_IRAM_OPT
#define CONFIG_ESP32_WIFI_ENABLE_WPA3_SAE                   CONFIG_ESP_WIFI_ENABLE_WPA3_SAE
#define CONFIG_ESP32_WIFI_ENABLE_WPA3_OWE_STA               CONFIG_ESP_WIFI_ENABLE_WPA3_OWE_STA
#define CONFIG_WPA_MBEDTLS_CRYPTO                           CONFIG_ESP_WIFI_MBEDTLS_CRYPTO
#define CONFIG_WPA_MBEDTLS_TLS_CLIENT                       CONFIG_ESP_WIFI_MBEDTLS_TLS_CLIENT
#define CONFIG_WPA_SUITE_B_192                              CONFIG_ESP_WIFI_SUITE_B_192
#define CONFIG_WPA_DEBUG_PRINT                              CONFIG_ESP_WIFI_DEBUG_PRINT
#define CONFIG_WPA_TESTING_OPTIONS                          CONFIG_ESP_WIFI_TESTING_OPTIONS
#define CONFIG_WPA_WPS_STRICT                               CONFIG_ESP_WIFI_WPS_STRICT
#define CONFIG_WPA_11KV_SUPPORT                             CONFIG_ESP_WIFI_11KV_SUPPORT
#define CONFIG_WPA_SCAN_CACHE                               CONFIG_ESP_WIFI_SCAN_CACHE
#define CONFIG_WPA_MBO_SUPPORT                              CONFIG_ESP_WIFI_MBO_SUPPORT
#define CONFIG_WPA_DPP_SUPPORT                              CONFIG_ESP_WIFI_DPP_SUPPORT
#define CONFIG_WPA_11R_SUPPORT                              CONFIG_ESP_WIFI_11R_SUPPORT
#define CONFIG_WPA_WPS_SOFTAP_REGISTRAR                     CONFIG_ESP_WIFI_WPS_SOFTAP_REGISTRAR
#define CONFIG_GPTIMER_ISR_IRAM_SAFE                        CONFIG_GPTIMER_ISR_CACHE_SAFE
#define CONFIG_ESP32C3_LIGHTSLEEP_GPIO_RESET_WORKAROUND     CONFIG_ESP_SLEEP_GPIO_RESET_WORKAROUND
#define CONFIG_ESP32C3_RTC_CLK_SRC_INT_RC                   CONFIG_RTC_CLK_SRC_INT_RC
#define CONFIG_ESP32C3_RTC_CLK_SRC_EXT_CRYS                 CONFIG_RTC_CLK_SRC_EXT_CRYS
#define CONFIG_ESP32C3_RTC_CLK_SRC_EXT_OSC                  CONFIG_RTC_CLK_SRC_EXT_OSC
#define CONFIG_ESP32C3_RTC_CLK_SRC_INT_8MD256               CONFIG_RTC_CLK_SRC_INT_8MD256
#define CONFIG_ESP32C3_RTC_CLK_CAL_CYCLES                   CONFIG_RTC_CLK_CAL_CYCLES
#define CONFIG_ESP32C3_TIME_SYSCALL_USE_RTC_SYSTIME         CONFIG_LIBC_TIME_SYSCALL_USE_RTC_HRT
#define CONFIG_ESP32C3_TIME_SYSCALL_USE_RTC                 CONFIG_LIBC_TIME_SYSCALL_USE_RTC
#define CONFIG_ESP32C3_TIME_SYSCALL_USE_SYSTIMER            CONFIG_LIBC_TIME_SYSCALL_USE_HRT
#define CONFIG_ESP32C3_TIME_SYSCALL_USE_NONE                CONFIG_LIBC_TIME_SYSCALL_USE_NONE
